/**
 * API client for the VTVL Simulator backend.
 *
 * TYPE CONTRACT — this project does not use OpenAPI or code-generated clients.
 * The interfaces defined in this file ARE the single source of truth for the
 * HTTP API contract between frontend and server. Any change to a server response
 * or request body shape MUST be reflected here.
 *
 * Key type distinctions:
 *  - RoomInfo           — shape returned by GET /rooms/:code (no hostSecret)
 *  - CreateRoomResponse — shape returned by POST /rooms (adds hostSecret)
 *  - SubmitRunPayload   — includes clientRunId for idempotent retries
 *
 * Authentication is handled exclusively via the HttpOnly session cookie that the
 * server sets on login/register. All requests are made with credentials:"include"
 * so the browser sends the cookie automatically — no bearer token is stored in
 * JavaScript-accessible storage.
 */
const API_BASE = "/api";

export interface UserInfo {
  id: string;
  username: string;
  email: string;
}

export interface RoomInfo {
  id: string;
  code: string;
  type: "coop" | "versus";
  missionId: string;
  status: string;
  hostId: string;
}

/**
 * Response from POST /rooms (room creation).
 * Extends RoomInfo with hostSecret — a server-issued credential returned
 * only to the creator and never exposed through GET /rooms/:code.
 * The creator must include this in the WebSocket join_room message to
 * claim host authority over the room.
 */
export interface CreateRoomResponse extends RoomInfo {
  hostSecret: string;
}

export interface LeaderboardEntry {
  id: string;
  displayName: string;
  userId?: string | null;
  missionId: string;
  score: number;
  grade: string;
  createdAt: string;
}

export interface PersonalBestEntry {
  displayName: string;
  missionId: string;
  score: number;
  grade: string;
  createdAt: string;
  /** 1-based rank within the returned page; null when outside it. */
  rank: number | null;
}

export interface LeaderboardResponse {
  entries: LeaderboardEntry[];
  personalBest: PersonalBestEntry | null;
}

export interface PlayerRun {
  id: string;
  missionId: string;
  score: number;
  grade: string;
  crashed: boolean;
  touchdownSpeed: number | null;
  padDeviation: number | null;
  fuelRemaining: number | null;
  tiltDeg: number | null;
  flightDuration: number | null;
  createdAt: string;
}

export interface PlayerStats {
  userId: string;
  username: string;
  totalFlights: number;
  bestScore: number | null;
  bestGrade: string | null;
  successRate: number;
}

export interface SubmitRunPayload {
  /**
   * Stable per-flight UUID generated by the client. The server uses this for
   * idempotency — retrying the same POST with the same clientRunId returns the
   * previously recorded result without inserting a duplicate row.
   */
  clientRunId?: string;
  missionId: string;
  guestName?: string;
  score: number;
  grade: string;
  crashed: boolean;
  touchdownSpeed?: number;
  padDeviation?: number;
  fuelRemaining?: number;
  tiltDeg?: number;
  flightDuration?: number;
}

async function apiFetch<T>(
  path: string,
  opts: RequestInit = {},
): Promise<T> {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };

  const res = await fetch(`${API_BASE}${path}`, {
    credentials: "include",
    headers,
    ...opts,
  });

  if (!res.ok) {
    const data = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(data?.error ?? `HTTP ${res.status}`);
  }
  return res.json() as Promise<T>;
}

export const api = {
  auth: {
    register: (username: string, email: string, password: string) =>
      apiFetch<{ user: UserInfo }>("/auth/register", {
        method: "POST",
        body: JSON.stringify({ username, email, password }),
      }),
    login: (email: string, password: string) =>
      apiFetch<{ user: UserInfo }>("/auth/login", {
        method: "POST",
        body: JSON.stringify({ email, password }),
      }),
    logout: () =>
      apiFetch<{ ok: boolean }>("/auth/logout", { method: "POST" }),
    me: () =>
      apiFetch<{ user: UserInfo | null }>("/auth/me"),
  },
  rooms: {
    create: (type: "coop" | "versus", missionId: string, guestName?: string) =>
      apiFetch<CreateRoomResponse>(
        "/rooms",
        { method: "POST", body: JSON.stringify({ type, missionId, guestName }) },
      ),
    get: (code: string) =>
      apiFetch<RoomInfo>(`/rooms/${code}`),
  },
  runs: {
    submit: (payload: SubmitRunPayload) =>
      apiFetch<{ id: string; leaderboardId: string | null }>(
        "/runs",
        { method: "POST", body: JSON.stringify(payload) },
      ),
  },
  leaderboard: {
    get: (missionId?: string, limit = 50, guestName?: string) => {
      const params = new URLSearchParams();
      if (missionId) params.set("missionId", missionId);
      params.set("limit", String(limit));
      if (guestName) params.set("guestName", guestName);
      return apiFetch<LeaderboardResponse>(`/leaderboard?${params}`);
    },
  },
  players: {
    stats: (userId: string) =>
      apiFetch<PlayerStats>(`/players/${userId}/stats`),
    runs: (userId: string, limit = 25) =>
      apiFetch<{ runs: PlayerRun[] }>(`/players/${userId}/runs?limit=${limit}`),
  },
};
